### ISSUE TITLE
Design suggestions

### ISSUE THREAD

**Issue by erosemberg** [CraftTogether/CraftCore#11]
So, current design is pretty bad, and if we continue doing it like this it will become a large mess of packages. 

Basically what i am suggesting is separating it into 2 modules, API and implementation, allows way more customization and a more professional design and scalable.

ktxhbye.

**Comment by Web2201** [comment]
Always been a fan of dem APIs. This could also save you a lot of headaches regarding imports or major method changes. For instance, a class out side of craftcore is using a class located in org.ctafttogether.player
If we for some reason decide to change the package of the class every plugin using the class would get rekt 360 noscoped. APIs FTW

**Comment by error-dan-overflow** [comment]
Good idea +1

**Comment by theminecoder** [comment]
Would we want to maybe have a core lib api that as no bukkit/bungee specific info and then depend on that for that for the actual plugins?

**Comment by Web2201** [comment]
Probably, that way we won't be restricted to only Bukkit plugins

**Comment by erosemberg** [comment]
@theminecoder Maven modules within the same project for the Core.

**Comment by joarc** [comment]
I think that just keeping every part of the core seperated in packages should be best for both new developers and making the plugin easy and simple.

**Comment by erosemberg** [comment]
Done.
