### ISSUE TITLE
Project Lombok

### ISSUE THREAD

**Issue by oliverdunk** [CraftTogether/CraftCore#2]
Generally I'd be inclined to use Project Lombok on a core plugin like this, as it makes it really easy to make larger classes smaller and at pretty much no cost. TravisCI also supports it through a Maven plugin so no need to worry about that.

The library: https://projectlombok.org/
Example: @Getter public int seven = 7; creates a method called getSeven() after making the variable;

**Comment by AKTheKnight** [comment]
I vote yay. However we do need to be careful and not just use it without thinking. Sometimes a better fledged getter/setter is more useful

**Comment by oliverdunk** [comment]
Definitely @AKTheKnight, I agree that it should only be used in place of basic, self describing methods and not as a replacement for those requiring additional logic.

**Comment by njb-said** [comment]
I was about to open an issue about this, good suggestion.
I agree with you @AKTheKnightht

**Comment by Rhonim** [comment]
Personally would vote no. The only thing it has led to in the past for me is complications. Most people won't know how to properly set it up for IntelliJ or Eclipse to compile it. Never personally liked it anyways.

**Comment by joarc** [comment]
I could see this as a usefull thing :+1:

**Comment by Flame10A** [comment]
I also vote no, having dealt with it before, I can only see it being a hassle.

**Comment by AKTheKnight** [comment]
React to this if you think YES, we should have lombok in CraftCore (We can debate the rest after)

**Comment by AKTheKnight** [comment]
React to this if you think NO, we should not have lombok in CraftCore (We can debate the rest after)

**Comment by erosemberg** [comment]
Most people use Lombok wrongly. My vote is a big round no.

**Comment by error-dan-overflow** [comment]
I vote yes, it saves so much time.

**Comment by andy1ne0** [comment]
I'd say no - it's impractical for use in a collaborative environment to any sort of scale. As JP said, many people won't know how to use it properly, and it's not reasonable to make contributors download a client plugin simply because we don't want to write the boilerplate codes [which would be an extra 30 seconds of work]. Not worth the trade-off.

**Comment by Flame10A** [comment]
As To add to that - IntelliJ, possibly other IDEs, already **_have_** tools to generate said boilerplate code.

**Comment by jakeycodes** [comment]
i'd say no on this one

**Comment by andy1ne0** [comment]
As Oli said, use alt+insert in IntelliJ for simple encapsulation generators: 

![](http://i.imgur.com/iWreBRi.png)

**Comment by theminecoder** [comment]
Seems to be a general no on this, so I am going to close the vote for now!
