### ISSUE TITLE
ProtocolLib

### ISSUE THREAD

**Issue by Desetude** [CraftTogether/CraftCore#25]
Are we going to be using ProtocolLib?

**Comment by andy1ne0** [comment]
Upvote this post if in favor of using ProtocolLib

**Comment by andy1ne0** [comment]
Upvote this post if against the use of ProtocolLib

**Comment by Rushmead** [comment]
This comes back to the whole inventory thing. We want to be using as much home made stuff as possible because its meant to be used as a learning experience for other people.

**Comment by Web2201** [comment]
If you want to recreate something that took years to perfect, go ahead. ProtocolLib is probably the most useful library out there and creating something that will replace it just for our own needs is quite silly.

**Comment by Musician101** [comment]
One more thing to consider is waiting on dependencies to update. Libraries like ProtocolLib would require us to wait for it to update before we can update the server as a whole

**Comment by theminecoder** [comment]
In the case of protocol lib, I'm personally inclined to use it to being with and them maybe shift over to something more custom if we need to, due to the time require to build such a core component.

**Comment by Musician101** [comment]
I can agree with that.

**Comment by njb-said** [comment]
Is there a need for it (custom or non-custom)
If we're just going to use it for the sake of it then it's not worth it, and if we're going to use it for one tiny feature it's equally not worth it.

As @Rushmead said above, we can discuss this literally every component and dependency.
If we're going to **actually use it** then we should have this discussion.

**Comment by theminecoder** [comment]
In the interest of time and progress on this project, when there is a need for something like this, ProtocolLib will be used.
