### ISSUE TITLE
Have a basic CraftPlayer object?

### ISSUE THREAD

**Issue by AKTheKnight** [CraftTogether/CraftCore#3]
What do people think about having a basic CraftPlayer object that we then use to put/pull from the database?

Anything in particular people want to be included. I reckon at a minimum:

UUID
Most recent username
Join Date
Currency
Any ranks

**Comment by Desetude** [comment]
Last known IP
Last join
Play time

**Comment by AKTheKnight** [comment]
Also, what are people's views on how we store a players info while they are on the server. Hashmap with Username and player info?

**Comment by Desetude** [comment]
Weak referenced keys concurrent hashmap with UUID to profile(or whatever we call the player data object).

**Comment by njb-said** [comment]
It wouldn't be a good idea to use usernames, UUID's are the way ahead.

**Comment by joarc** [comment]
I agree with @Desetude , having an "player" data object that is linked to a uuid would probably be best way to handle the data about players.

**Comment by AKTheKnight** [comment]
Sounds good. Just throwing out ideas :)

**Comment by erosemberg** [comment]
All known usernames
All known ip adresses
Last known ip & name
First join date
Last join data
Currency(s)
Rank/Permission(s)
UUID
Actual Player reference

all of this being thread safe ofc.

**Comment by error-dan-overflow** [comment]
I think everything @erosemberg mentioned is good, and maybe punishment information should be stored as well.

**Comment by theminecoder** [comment]
The only thing we need to worry about is updating the play objects as actions may be performed on other servers/website and we need that to show as quick as possible in game.

**Comment by Web2201** [comment]
@theminecoder Redis <3

**Comment by theminecoder** [comment]
Well here's the thing, i know redis is cool and all but i found something just that much cooler. About to make a vote issue for it :P (And plus technically rethink's change api could keep us up to date as well but ya know)

**Comment by Web2201** [comment]
There is something cooler than Redis?!?!?!

**Comment by theminecoder** [comment]
CraftTogether/Discussion-Issues#14 @Web2201
